### ISSUE TITLE
most descriptors are all ones when using keypoints from cv::goodFeatureToTrack()

### ISSUE THREAD

**Issue by Natalie-ZG** [iago-suarez/BEBLID#1]
Excuse me. Thanks for sharing the excellent work.

When I use BEBLID to extract descriptors for keypoints from cv::goodFeaturesToTrack(), I find that many descriptors are all ones. I have tried all optional parameters but get similar results. 

Is it related to training process? Would you please help me with my confusion? Thanks a lot.

**Comment by jmbuena** [comment]
One of the most important parameters for this descriptor to work is the size of the keypoint. Take into account that we have trained BEBLID with fixed size patches from the Liberty scene (Brown dataset) and the size of the patch around the keypoint should match with the ones in training.

We have tested [scale factors](https://docs.opencv.org/master/d7/d99/classcv_1_1xfeatures2d_1_1BEBLID.html) for some detectors and found that multiplying the detector size of the keypoint by an scale factor with value:

   -  1.00f should be the scale for ORB keypoints
   -  6.75f should be the scale for SIFT detected keypoints
   -  6.25f is default and fits for KAZE, SURF detected keypoints
   -  5.00f should be the scale for AKAZE, MSD, AGAST, FAST, BRISK keypoints

allows to have a patch compatible with the trained ones. I think we have not tested the "Good Features to track" detector.

Can you tray different scale factor values and see if there is any difference?

**Comment by xushangnjlh** [comment]
> One of the most important parameters for this descriptor to work is the size of the keypoint. Take into account that we have trained BEBLID with fixed size patches from the Liberty scene (Brown dataset) and the size of the patch around the keypoint should match with the ones in training.
> 
> We have tested [scale factors](https://docs.opencv.org/master/d7/d99/classcv_1_1xfeatures2d_1_1BEBLID.html) for some detectors and found that multiplying the detector size of the keypoint by an scale factor with value:
> 
> * 1.00f should be the scale for ORB keypoints
> * 6.75f should be the scale for SIFT detected keypoints
> * 6.25f is default and fits for KAZE, SURF detected keypoints
> * 5.00f should be the scale for AKAZE, MSD, AGAST, FAST, BRISK keypoints
> 
> allows to have a patch compatible with the trained ones. I think we have not tested the "Good Features to track" detector.
> 
> Can you tray different scale factor values and see if there is any difference?

Seems 6.25 is the optimal for GFTT

**Comment by jmbuena** [comment]
> Can you tray different scale factor values and see if there is any difference?
> 
> Seems 6.25 is the optimal for GFTT

Thanks a lot for trying it and finding the right scale!
