### ISSUE TITLE
Can BEBLID be used for real-time video stitching?

### ISSUE THREAD

**Issue by MambaCtrl** [iago-suarez/BEBLID#3]

**Comment by jmbuena** [comment]
Yes, I don't see why not. As long as your local feature detector (e.g. ORB or FAST) can find de features efficiently, you can put BEBLID descriptor on top to perform matching. Then with OpenCV's findHomography you can align every pair of images.

The nice thing about BEBLID is that is as efficient as ORB but it works better in the cases where the view is very different between the pair of images.

Regards,
JM

**Comment by MambaCtrl** [comment]
> 是的，我不明白为什么不。只要您的本地特征检测器（例如 ORB 或 FAST）可以有效地找到 de 特征，您就可以将 BEBLID 描述符放在最上面进行匹配。然后使用 OpenCV 的 findHomography，您可以对齐每对图像。
> 
> BEBLID 的好处在于它与 ORB 一样高效，但在图像对之间的视图非常不同的情况下效果更好。
> 
> 问候， JM

Thanks

**Comment by jmbuena** [comment]
I assume that you have images taken with a camera only making a rotation (i.e. in a tripod) and then you can use findHomography.

JM.

**Comment by MambaCtrl** [comment]
> 

I have two cameras, the two cameras are parallel, I want to combine the live video of the two cameras into one video, which requires high real-time

**Comment by jmbuena** [comment]
BEBLID descriptor is really fast and better than ORB ... so, yes you can use it instead of ORB descriptor.

**Comment by MambaCtrl** [comment]
> BEBLID descriptor is really fast and better than ORB ... so, yes you can use it instead of ORB descriptor.

Thanks！
