### ISSUE TITLE
Keypoint Scale for HPatches?

### ISSUE THREAD

**Issue by xushangnjlh** [iago-suarez/BEBLID#4]
Thank you for sharing this wonderful work!
I am testing your results on HPatches, however I am not sure which keypoint scale (sampling window) you utilized when testing BEBLID descriptor. I noticed that you have mentioned a recommended scale for different keypoint (so I set 6.75 for hpatches). But the resulting matching mAP is only 0.13.
![image](https://user-images.githubusercontent.com/17842984/189867669-1599a17b-c5e4-41c5-9135-cd85b2f11850.png)

So what are the scale settings for you when evaluating on hpatches? Thanks in advance!

**Comment by iago-suarez** [comment]
Hi,

I assume that you are using the OpenCV Python version and that you are using pre-cropped patches. Is this right?

If so, for the 32x32 patches, the keypoint should be centered in the point `(16, 16)` and the `scale=1.0`. This is what we have tested in the paper. If you use patches of size 64x64 then the center should be `(32, 32)` and the `scale=2.0`. I hope this is helpful for you. If you are not able to reproduce the results and can send you a small example, but I'm not sure when I'll have time to do it.

**Comment by xushangnjlh** [comment]
It would be great if you can send me the example (xushangnjlh@gmail.com). As for HPatches, default patch size is 65x65 and when I set keypoint scale to 2.0, the results get even worse and I cannot figure out why ...
Thanks and take your time~

**Comment by iago-suarez** [comment]
Okey, I'll try to do it this weekend! I will also publish it here because I think is beneficial for the community.

Best,
Iago.

**Comment by iago-suarez** [comment]
Hi @xushangnjlh ,

Sorry for late reply. My time is scarce and this type of thing takes time. Here you can find a python notebook where I leave you the instructions to reproduce the paper results.

https://colab.research.google.com/github/iago-suarez/beblid-opencv-demo/blob/main/beblid_hpatches.ipynb

The figure is exactly the same as the one in [the paper](https://github.com/iago-suarez/BEBLID/blob/master/BEBLID_Boosted_Efficient_Binary_Local_Image_Descriptor.pdf) and BEBLID obtain the same results.

![image](https://user-images.githubusercontent.com/7408877/207463180-77646a6e-91f6-49c3-aab1-a057382a85de.png)

I hope you find this useful :)

Best,
Iago.
